name: Bug report
description: Create a report to help us improve
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the bug/behavior.
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expectedbhv
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshot/ Video
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Portfolio/blob/main/CODE_OF_CONDUCT.md) 🖖
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        ---
        If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
        Feel free to check out other cool **open-source** repositories and communities:
          [Kabir0x23](https://github.com/kabir0x23) • [Cryptoverse Web3](https://github.com/CryptoverseWeb3) • [Thecyberworld](https://github.com/thecyberworld)
